[tool.poetry]
name = "media-labs"
version = "0.1.0"
description = ""
authors = ["Mykola Petrychkevych <m.petrychkevych@soloway.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydub = "^0.25.1"
mutagen = "^1.47.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
