[tool.poetry]
name = "media-labs"
version = "0.1.0"
description = ""
authors = ["Mykola Petrychkevych <m.petrychkevych@soloway.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
pydub = "^0.25.1"
mutagen = "^1.47.0"
boto3 = "^1.41.1"
requests = "^2.32.5"
awscli = "^1.43.1"
langdetect = "^1.0.9"
nltk = "^3.9.2"
spacy = "^3.8.11"
opencv-python = "^4.12.0.88"
pillow = "^12.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
